# Generated by Django 2.1 on 2020-06-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200630_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Science', 'Science'), ('Arts', 'Arts'), ('Commerce', 'Commerce'), ('Engineering', 'Engineering')], default='Arts', max_length=100),
        ),
    ]
