# Generated by Django 2.1 on 2020-07-10 07:35

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200707_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Address',
            field=models.TextField(default='contact me via call'),
        ),
        migrations.AddField(
            model_name='post',
            name='Contact_no',
            field=phonenumber_field.modelfields.PhoneNumberField(default='XXXXXXXXXXX', max_length=128, region=None),
        ),
    ]
